[package]
name = "async-tar"
version = "0.7.0"
authors = ["dignifiedquire <me@dignifiequire.com>", "Alex Crichton <alex@alexcrichton.com>"]
homepage = "https://github.com/dignifiedquire/async-tar"
repository = "https://github.com/dignifiedquire/async-tar"
documentation = "https://docs.rs/async-tar"
license = "MIT OR Apache-2.0"
keywords = ["tar", "tarfile", "encoding", "async", "smol", "tokio"]
readme = "README.md"
edition = "2024"
rust-version = "1.85"

description = """
A Rust implementation of an async TAR file reader and writer. This library does not
currently handle compression, but it is abstract over all I/O readers and
writers. Additionally, great lengths are taken to ensure that the entire
contents are never required to be entirely resident in memory all at once.
"""

[dependencies]
smol =  { version = "2.0.2", optional = true }
tokio = { version = "1.49", optional = true, features = ["fs", "io-util"] }
filetime = "0.2.27"
tokio-stream = { version = "0.1.18", features = ["fs"], optional = true }

[dev-dependencies]
tokio = { version = "1.49", features = ["rt", "io-std", "rt-multi-thread", "macros"] }
static_assertions = "1.1"
tempfile = "3.24"
macro_rules_attribute = "0.2.2"
smol-macros = "0.1.1"


[target."cfg(unix)".dependencies]
libc = "0.2"
xattr = { version = "1.6", optional = true }

# TODO: remove as done in tar-rs
[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.7"

[features]
default = ["xattr", "runtime-smol"]
runtime-smol = ["smol"]
runtime-tokio = ["tokio", "tokio-stream"]
